title: Assistance for Training Technologies & Ideas (ATTI)
description: Welcome to Assistance for Training Technologies & Ideas (ATTI)

baseurl: /
color-scheme: "cornflowerblue" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
